services:
  autoscaler:
    image: ghcr.io/crimeisdown/trunk-transcribe:${VERSION:-main}
    build:
      context: .
      dockerfile: docker/Dockerfile
      cache_from:
        - ghcr.io/crimeisdown/trunk-transcribe:main
    command:
      - app/bin/autoscale-vast.py
      - --min-instances
      - ${AUTOSCALE_MIN_INSTANCES:-1}
      - --max-instances
      - ${AUTOSCALE_MAX_INSTANCES:-10}
      - --interval
      - ${AUTOSCALE_INTERVAL:-60}
      - --image
      - ghcr.io/crimeisdown/whisper-asr-webservice:latest-gpu
    env_file: .env
    volumes:
      - ./app:/src/app
      - ./config:/src/config
      - ./.env.vast:/src/.env.vast
      - ~/.vast_api_key:/root/.vast_api_key
    restart: always

  haproxy:
    image: haproxy:latest
    volumes:
      - ./docker/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    restart: always

  api:
    environment:
      - ASR_API_URL=http://haproxy:9000
      - HAPROXY_STATS_ADDRESS=haproxy:8444
