services:

  minio:
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET
    entrypoint: /bin/bash
    command: /usr/bin/minio-entrypoint.sh
    volumes:
      - minio-storage:/data
      - ./bin/minio-entrypoint.sh:/usr/bin/minio-entrypoint.sh
    restart: always

volumes:
  minio-storage:
