services:
  worker-whisper:
    image: ghcr.io/crimeisdown/trunk-transcribe:${VERSION:-main}-${WHISPER_IMPLEMENTATION:-whisper}-${WHISPER_MODEL:-small.en}-cuda_${CUDA_VERSION:-12.1.0}
    build:
      context: .
      dockerfile: docker/${WORKER_DOCKERFILE:-Dockerfile.whisper}
      cache_from:
        - ghcr.io/crimeisdown/trunk-transcribe:main-${WHISPER_IMPLEMENTATION:-whisper}-${WHISPER_MODEL:-small.en}-cuda_${CUDA_VERSION:-12.1.0}
      args:
        WHISPER_MODEL: ${WHISPER_MODEL:-small.en}
    command: worker
    volumes:
      - ./backend/app:/src/backend/app
      - ./backend/alembic.ini:/src/backend/alembic.ini
      - ./backend/pyproject.toml:/src/backend/pyproject.toml
      - ./config:/src/config
      - ./docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    environment:
      - DEFAULT_TRANSCRIPTION_BACKEND=${DEFAULT_TRANSCRIPTION_BACKEND:-whisper}
      - TRANSCRIPTION_BACKEND=whisper
      - CELERY_QUEUES=transcribe_whisper
      - CELERY_LOGLEVEL
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
      - CELERY_CONCURRENCY
      - CELERY_PREFETCH_MULTIPLIER
      - WHISPER_IMPLEMENTATION
      - WHISPER_MODEL
      - ASR_API_URL
    env_file: .env
    restart: always
