services:
  autoscaler:
    image: ghcr.io/crimeisdown/trunk-transcribe:${VERSION:-main}
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - ghcr.io/crimeisdown/trunk-transcribe:main
    command:
      - poetry
      - run
      - app/bin/autoscale-vast.py
      - --min-instances
      - ${AUTOSCALE_MIN_INSTANCES:-1}
      - --max-instances
      - ${AUTOSCALE_MAX_INSTANCES:-10}
      - --interval
      - ${AUTOSCALE_INTERVAL:-60}
      - --image
      - ghcr.io/crimeisdown/trunk-transcribe:main-${WHISPER_IMPLEMENTATION:-whisper}-${WHISPER_MODEL:-large-v2}-${DESIRED_CUDA:-cu121}
    env_file: .env
    volumes:
      - ./app:/src/app
      - ./config:/src/config
      - ~/.vast_api_key:/root/.vast_api_key
    restart: always
