version: '3.8'

services:
  autoscaler:
    image: crimeisdown/trunk-transcribe:${VERSION:-main}
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - ./autoscale-vast.py
      - --min-instances
      - ${AUTOSCALE_MIN_INSTANCES:-1}
      - --max-instances
      - ${AUTOSCALE_MAX_INSTANCES:-10}
      - --interval
      - ${AUTOSCALE_INTERVAL:-60}
    environment:
      - VAST_API_KEY
      - SENTRY_DSN
      - FLOWER_URL=http://flower:5555
    volumes:
      - ./bin/autoscale-vast.py:/src/autoscale-vast.py
      - ./.env.vast:/src/.env.vast
      - ~/.vast_api_key:/root/.vast_api_key
    restart: always
