version: '3.8'

services:

  worker:
    image: ghcr.io/crimeisdown/trunk-transcribe:${VERSION:-main}
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - ghcr.io/crimeisdown/trunk-transcribe:main
      args: []
    command: worker
