services:
  worker:
    image: ghcr.io/crimeisdown/trunk-transcribe:${VERSION:-main}-${WHISPER_IMPLEMENTATION:-whisper}-${WHISPER_MODEL:-small.en}-${DESIRED_CUDA:-cpu}
    build:
      context: .
      dockerfile: docker/${WORKER_DOCKERFILE:-Dockerfile.whisper}
      cache_from:
        - ghcr.io/crimeisdown/trunk-transcribe:main-${WHISPER_IMPLEMENTATION:-whisper}-${WHISPER_MODEL:-small.en}-${DESIRED_CUDA:-cpu}
      args:
        WHISPER_MODEL: ${WHISPER_MODEL:-small.en}
    volumes:
      - ./app:/src/app
      - ./config:/src/config
      - ./docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    env_file: .env
    restart: always
