services:
  worker:
    image: ghcr.io/crimeisdown/trunk-transcribe:${VERSION:-main}
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      cache_from:
        - ghcr.io/crimeisdown/trunk-transcribe:main
    command: worker
    volumes:
      - ./app:/src/app
      - ./config:/src/config
      - ./docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    env_file: .env
    restart: always
