services:

  whisper:
    image: ghcr.io/crimeisdown/whisper-asr-webservice:latest-gpu
    environment:
      - ASR_ENGINE=${ASR_ENGINE:-openai_whisper}
      - ASR_MODEL=${WHISPER_MODEL:-large-v2}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
