version: '3.8'

services:

  web:
    image: crimeisdown/trunk-transcribe:main-tiny.en-cpu
    ports:
      - 8000:8000
    command: web
    volumes:
      - ./app:/src/app
      - ./config:/src/config
      - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    env_file: .env
    restart: always

  worker:
    image: crimeisdown/trunk-transcribe:main-${WHISPER_MODEL:-medium.en}-${DESIRED_CUDA:-cu117}
    command: worker
    volumes:
      - ./app:/src/app
      - ./config:/src/config
      - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    env_file: .env
    restart: always

  dashboard:
    image: crimeisdown/trunk-transcribe:main-tiny.en-cpu
    command: flower
    volumes:
      - ./flowerconfig.py:/src/flowerconfig.py
      - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - flowerdb:/src/data
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
      - FLOWER_PURGE_OFFLINE_WORKERS=120
      - FLOWER_PERSISTENT=1
      - FLOWER_DB=/src/data/flower
      - FLOWER_STATE_SAVE_INTERVAL=30000
      - FLOWER_BROKER_API
    restart: always

  broker:
    image: rabbitmq:3-management
    volumes:
      - broker-data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    restart: always

  meilisearch:
    image: 'getmeili/meilisearch:latest'
    ports:
      - 7700:7700
    environment:
      - MEILI_MASTER_KEY
    volumes:
      - meilisearch-data:/meili_data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
      retries: 3
      timeout: 5s

volumes:
  flowerdb:
  broker-data:
  meilisearch-data:
