version: '3.8'

services:

  web:
    image: crimeisdown/trunk-transcribe:main-${WHISPER_MODEL}
    ports:
      - 8000:8000
    command: web
    volumes:
      - ./app:/src/app
      - ./config:/src/config
      - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    env_file: .env
    restart: always

  worker:
    image: crimeisdown/trunk-transcribe:main-${WHISPER_MODEL}
    command: worker
    volumes:
      - ./app:/src/app
      - ./config:/src/config
      - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    env_file: .env
    restart: always

  dashboard:
    image: crimeisdown/trunk-transcribe:main-${WHISPER_MODEL}
    command: flower
    volumes:
      - ./flowerconfig.py:/src/flowerconfig.py
      - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - flowerdb:/src/data
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
      - FLOWER_PURGE_OFFLINE_WORKERS=1
      - FLOWER_PERSISTENT=1
      - FLOWER_DB=/src/data/flower
      - FLOWER_STATE_SAVE_INTERVAL=30000
      - FLOWER_BROKER_API
    restart: always

  broker:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    restart: always

  typesense:
    image: typesense/typesense:0.23.1
    ports:
      - 8108:8108
    environment:
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_API_KEY
      - TYPESENSE_ENABLE_CORS
      - TYPESENSE_CORS_DOMAINS
    volumes:
      - typesense-data:/data

volumes:
  flowerdb:
  typesense-data:
