version: '3.8'

services:

  api:
    image: ghcr.io/crimeisdown/trunk-transcribe:${VERSION:-main}
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - ghcr.io/crimeisdown/trunk-transcribe:main
    ports:
      - 8000:8000
    command: api
    volumes:
      - ./app:/src/app
      - ./config:/src/config
      - ./tests:/src/tests
      - ./bin/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    env_file: .env
    restart: always

  worker:
    image: ghcr.io/crimeisdown/trunk-transcribe:${VERSION:-main}-${WHISPER_MODEL:-small.en}-${DESIRED_CUDA:-cpu-cpp}
    build:
      context: .
      dockerfile: ${WORKER_DOCKERFILE:-Dockerfile.whispercpp}
      cache_from:
        - ghcr.io/crimeisdown/trunk-transcribe:main-${WHISPER_MODEL:-small.en}-${DESIRED_CUDA:-cpu-cpp}
      args:
        WHISPER_MODEL: ${WHISPER_MODEL:-small.en}
    volumes:
      - ./app:/src/app
      - ./config:/src/config
      - ./bin/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    env_file: .env
    restart: always

  flower:
    image: ghcr.io/crimeisdown/trunk-transcribe:${VERSION:-main}
    command: flower
    volumes:
      - ./bin/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - flower-data:/src/data
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
      - CELERY_QUEUES=transcribe,retranscribe
      - FLOWER_PURGE_OFFLINE_WORKERS=120
      - FLOWER_PERSISTENT=1
      - FLOWER_DB=/src/data/flower
      - FLOWER_STATE_SAVE_INTERVAL=30000
      - FLOWER_BROKER_API
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    restart: always

  meilisearch:
    image: 'getmeili/meilisearch:v1.3.1'
    ports:
      - 7700:7700
    environment:
      - MEILI_MASTER_KEY
    volumes:
      - meilisearch-data:/meili_data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
      retries: 3
      timeout: 5s
    restart: always

volumes:
  flower-data:
  rabbitmq-data:
  meilisearch-data:
