services:

  whisper:
    image: ghcr.io/crimeisdown/whisper-asr-webservice:latest-gpu
    environment:
      - ASR_ENGINE=${ASR_ENGINE:-openai_whisper}
      - ASR_MODEL=${WHISPER_MODEL:-large-v2}
    volumes:
      - cache-whisper:/root/.cache/whisper
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

volumes:
  cache-whisper:
