name: Publish Docker Image
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: ["base.en", "small.en", "medium.en"]
        platform: ["linux/amd64"]
        desired_cuda: ["cu117"]
        include:
          - model: tiny.en
            platform: linux/amd64
            desired_cuda: cpu
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Publish the Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: "${{ secrets.REPO_NAME }}:${{ github.ref_name }}-${{ matrix.model }}-${{ matrix.desired_cuda }}"
        platforms: ${{ matrix.platform }}
        build-args: |
          WHISPER_MODEL=${{ matrix.model }}
          DESIRED_CUDA=${{ matrix.desired_cuda }}
          GIT_COMMIT=${{ github.sha }}
        cache-from: type=registry,ref=${{ secrets.REPO_NAME }}:${{ github.ref_name }}-${{ matrix.model }}-${{ matrix.desired_cuda }}
        cache-to: type=inline
