name: Publish Docker Image
on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - 'app/**'
      - 'bin/*.sh'
      - 'config/**'
      - 'Dockerfile'
      - 'Dockerfile.whisper'
      - 'Dockerfile.whispercpp'
      - 'install-whisper.sh'
      - 'requirements.txt'
      - 'requirements-dev.txt'
      - '.github/workflows/docker-publish.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["linux/amd64"]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Publish the Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}"
        platforms: ${{ matrix.platform }}
        build-args: |
          GIT_COMMIT=${{ github.sha }}
        cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
        cache-to: type=inline
  build-worker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # GPU variants
        model: ["base.en", "small.en", "medium.en", "large"]
        platform: ["linux/amd64"]
        desired_cuda: ["cu117"]
        # desired_cuda: ["cu116", "cu117"]
        dockerfile: ["Dockerfile.whisper"]
        # CPU variants
        include:
          - model: tiny.en
            platform: linux/amd64
            desired_cuda: cpu
            dockerfile: Dockerfile.whisper
          - model: base.en
            platform: linux/amd64
            desired_cuda: cpu-cpp
            dockerfile: Dockerfile.whispercpp
          - model: small.en
            platform: linux/amd64
            desired_cuda: cpu-cpp
            dockerfile: Dockerfile.whispercpp
          - model: medium.en
            platform: linux/amd64
            desired_cuda: cpu-cpp
            dockerfile: Dockerfile.whispercpp
          - model: large
            platform: linux/amd64
            desired_cuda: cpu-cpp
            dockerfile: Dockerfile.whispercpp
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Publish the Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        push: true
        tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-${{ matrix.model }}-${{ matrix.desired_cuda }}"
        platforms: ${{ matrix.platform }}
        build-args: |
          WHISPER_MODEL=${{ matrix.model }}
          DESIRED_CUDA=${{ matrix.desired_cuda }}
          GIT_COMMIT=${{ github.sha }}
        cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-${{ matrix.model }}-${{ matrix.desired_cuda }}
        cache-to: type=inline
