name: Publish Docker Image
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: [tiny.en, small.en, medium.en]
        platform: [linux/amd64]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Publish the Docker image
      run: |
        DOCKER_IMAGE_VERSION=$REPO_NAME:$GITHUB_REF_NAME-${{ matrix.model }}
        docker pull "${DOCKER_IMAGE_VERSION}"
        docker buildx build . --cache-from="${DOCKER_IMAGE_VERSION}" --platform=${{ matrix.platform }} --build-arg WHISPER_MODEL=${{ matrix.model }} -t "${DOCKER_IMAGE_VERSION}" --push
