name: Build Docker Image
on:
  workflow_dispatch:
  release:
    types: [created]
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'docker/**'
      - 'config/**'
      - 'Dockerfile*'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/docker-publish.yml'
  # pull_request:
  #   branches:
  #     - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: crimeisdown/trunk-transcribe
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["linux/amd64"]
    steps:
    # https://github.com/orgs/community/discussions/25678#discussioncomment-5242449
    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build image
      if: github.ref != 'refs/heads/main' && github.event_name != 'release'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile
        load: true
        tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
        platforms: ${{ matrix.platform }}
        build-args: |
          GIT_COMMIT=${{ github.sha }}
        cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        cache-to: type=inline
    - name: Build and push
      if: github.ref == 'refs/heads/main' || github.event_name == 'release'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile
        push: true
        tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}"
        platforms: ${{ matrix.platform }}
        build-args: |
          GIT_COMMIT=${{ github.sha }}
        cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
        cache-to: type=inline
